### PR TITLE
Add support of extend and block in EJS

### PR DESCRIPTION
**Pull request by ictliujie**
@visionmedia, fyi:
Add features of extend and block, which could support 
(1) multilayer inheritance, fully support layout in EJS.
(2) Also could work with include. 
The examples and test has also been add!

### CODE REVIEW

**Comment by calidion** [comment]
what is the progress on this?

**Comment by huxia** [comment]
guys, here is my block implementation for the new ejs.
https://github.com/mde/ejs/issues/252

**Comment by rossrossp** [comment]
Is anything happening with this?

**Comment by MohitKumar1991** [comment]
Has this support been added ?

**Comment by mde** [comment]
This version of EJS is no longer maintained. The current version, installable via NPM, is here: https://github.com/mde/ejs

**Pull request closed without merging**
